[package]
name = "beancount_generator"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
wasm-bindgen = "0.2"